const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.Spawn
	];
};
self.C3_JsPropNameTable = [
	{cenario: 0},
	{Sprite: 0},
	{MovimentoEmGrid: 0},
	{Nico: 0},
	{Sólido: 0},
	{Sprite4: 0},
	{Projétil: 0},
	{municao: 0},
	{arma: 0},
	{Teclado: 0},
	{gato: 0},
	{Sprite5: 0},
	{ratoeira: 0},
	{cabeca1: 0},
	{cabeca2: 0},
	{cabeca3: 0},
	{Esmaecer: 0},
	{fadein: 0},
	{direcao: 0},
	{vidaNico: 0},
	{vidaGato: 0},
	{FimDaFase: 0}
];

self.InstanceType = {
	cenario: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Nico: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	municao: class extends self.ISpriteInstance {},
	arma: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	gato: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	ratoeira: class extends self.ISpriteInstance {},
	cabeca1: class extends self.ISpriteInstance {},
	cabeca2: class extends self.ISpriteInstance {},
	cabeca3: class extends self.ISpriteInstance {},
	fadein: class extends self.ISpriteInstance {}
}