const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Cnds.CompareOpacity
	];
};
self.C3_JsPropNameTable = [
	{cenario: 0},
	{Sprite: 0},
	{Gato: 0},
	{MovimentoEmGrid: 0},
	{Nico: 0},
	{Sólido: 0},
	{colisao: 0},
	{Projétil: 0},
	{municao: 0},
	{arma: 0},
	{Teclado: 0},
	{ratoeira: 0},
	{vida1: 0},
	{vida2: 0},
	{vida3: 0},
	{Esmaecer: 0},
	{fade: 0},
	{morte: 0},
	{Sprite2: 0},
	{Texto: 0},
	{direcao: 0},
	{VidaGato: 0},
	{VidaNico: 0},
	{gameOver: 0}
];

self.InstanceType = {
	cenario: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Gato: class extends self.ISpriteInstance {},
	Nico: class extends self.ISpriteInstance {},
	colisao: class extends self.ISpriteInstance {},
	municao: class extends self.ISpriteInstance {},
	arma: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	ratoeira: class extends self.ISpriteInstance {},
	vida1: class extends self.ISpriteInstance {},
	vida2: class extends self.ISpriteInstance {},
	vida3: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	morte: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {}
}